query characters($limit: Int, $filter: FilterCharacter) {
  characters(page: $limit, filter: $filter) {
    info {
      count
      pages
      next
      prev
    }
    results {
      id
      name
      image
      species
      gender
      origin {
        name
      }
    }
  }
}
